version: '3'
services:
  mariadb:
    container_name: mariadb
    networks:
      - inception
    build:
      context: ./requirements/mariadb
    volumes: 
      - mariadb:/var/lib/mysql
    env_file: .env
    restart: unless-stopped
    expose:
      - "3306"

  nginx:
    container_name: nginx
    volumes:
      - wordpress:/var/www/html
    networks:
      - inception
    depends_on:
      - wordpress
    build:
      context: requirements/nginx
    env_file: .env
    ports:
      - "443:443"
    restart: on-failure

  wordpress:
    container_name: wordpress
    build:
      context: ./requirements/wordpress
    depends_on:
      - mariadb
    restart: on-failure
    volumes:
      - wordpress:/var/www/html
    networks:
      - inception
    env_file: .env
    depends_on:
      - mariadb
    expose:
      - "9000"

networks:
  inception:
    driver: bridge

volumes:
  wordpress:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/antbarbi/data/html
  mariadb:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/antbarbi/data/mariadb
