version: "3.9"
services:
  mariadb:
    build:
      context: ./requirements/mariadb
    restart: always
    volumes: 
      - wp_db:/var/lib/mysql
    networks:
      - wp_db
    env_file: .env
    expose:
      - "3306"

  wordpress:
    build:
      context: ./requirements/wordpress
    restart: always
    volumes:
      - wp-files:/var/www/html
    networks:
      - wp_web
      - wp_db
    env_file: .env
    depends_on:
      - mariadb
    expose:
      - "9000"

  nginx:
    build: 
      context: ./requirements/wordpress
    depends_on:
      - wordpress
    restart: always
    env_file: .env
    volumes: 
      - wp-files:/var/www/html
    networks: 
      - wp_web
    ports: 
      - "443:443"

networks:
  wp_db:
    driver: bridge
  wp_web:
    driver: bridge

volumes:
  wp-files:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /home/antbarbi/data/wp-files

  wp_db:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /home/antbarbi/data/db

